version: '3'


services:

  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27017:27017'

  gochanges:
    restart: always
    build: .
    environment:
      - FILE_NAME="./example/example1.txt"
      - MONGO_CONN="mongodb://127.0.0.1:27017"
      - DB_NAME="gochangesdb"