version: '3'


services:

  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    volumes:
      - /mongo-volume:/data/db
    ports:
      - '27017:27017'

  gochanges:
    restart: always
    build: .
    ports:
     - "8080:8080"